name: Deploy

on:
  push:
    branches:
      - main
jobs:
  custom-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Heroku login credentials
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: $HEROKU_API_KEY
          heroku_app_name: $HEROKU_APP_NAME
          heroku_email: $HEROKU_EMAIL
          justlogin: true
      - run: heroku auth:whoami
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: "lidor5500@gmail.com"
          HEROKU_APP_NAME: "presence-board-echo"
      - name: Add Heroku remote
        run: |
          heroku git:remote --app $HEROKU_APP_NAME
          heroku config:set NODE_ENV=prod --app $HEROKU_APP_NAME
          heroku config:set ENVIRONMENT=prod --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: "presence-board-echo"
      - name: Push to Heroku
        run: git push heroku master
