name: Deploy

on:
  push:
    branches:
      - main
jobs:
  custom-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Heroku login credentials
        run: |
          cat <<< 'machine api.heroku.com\n login $HEROKU_EMAIL\n password $HEROKU_API_KEY\nmachine git.heroku.com\n login $HEROKU_EMAIL\n password $HEROKU_API_KEY' > ~/.netrc
        env:
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - run: |
          heroku auth:whoami
      - name: Add Heroku remote
        run: |
          heroku git:remote --app $HEROKU_APP_NAME
          heroku config:set NODE_ENV=prod --app $HEROKU_APP_NAME
          heroku config:set ENVIRONMENT=prod --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - name: Push to Heroku
        run: git push heroku master
